//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMeasure
    {
        public UnitMeasure()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.Product = new HashSet<Product>();
            this.Product1 = new HashSet<Product>();
            this.ProductVendor = new HashSet<ProductVendor>();
        }
    
        public string UnitMeasureCode { get; set; }
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual ICollection<ProductVendor> ProductVendor { get; set; }
    }
}
